Repository FE-tech-talk/TechTalk-React, pull requests merged in 2024-05, with the labels that each got.

#1 [이지현-1장] 내용 정리
  01. JS/이지현/1. 자바스크립트의 동등 비교.md
  01. JS/이지현/2. 함수.md
  01. JS/이지현/3. 클래스.md
  01. JS/이지현/4. 클로저.md
  01. JS/이지현/5. 이벤트 루프와 비동기 통신의 이해.md
  01. JS/이지현/6. 리액트에서 자주 사용하는 자바스크립트 문법.md
  01. JS/이지현/7. 선택이 아닌 필수, 타입스크립트.md
Labels: 🥹 이지현

#10 📚 Docs: 챕터 2 내용 정리
  02. React/이지현/1. JSX란?.md
  02. React/이지현/2. 가상 DOM과 리액트 파이버.md
  02. React/이지현/3. 클래스 컴포넌트와 함수 컴포넌트.md
  02. React/이지현/4. 렌더링은 어떻게 일어나는가?.md
  02. React/이지현/5. 컴포넌트와 함수의 무거운 연산을 기억해 두는 메모이제이션.md
Labels: 🥹 이지현 🥹

#8 docs: 장혜민 1, 2장 요약
  01. JS/장혜민/1주차_요약1.md
  02. React/2주차_요약1.md
Labels: 장혜민

#15 📚 docs: chapter 2 이승현
  01. JS/이승현/index.md
  02. React/이승현/1.md
  02. React/이승현/2.md
  02. React/이승현/3.md
  02. React/이승현/4.md
  02. React/이승현/5.md
  02. React/이승현/image/20240527_165636.jpg
  02. React/이승현/image/20240528_130847.jpg
  02. React/이승현/image/20240528_130854.jpg
  02. React/이승현/image/20240528_131211.jpg
  02. React/이승현/image/Deep dive 2_240527_164701_1.jpg
  02. React/이승현/image/Deep dive 2_240527_164701_2.jpg
  02. React/이승현/image/Deep dive 2_240527_202737.jpg
  02. React/이승현/image/Deep dive 2_240528_130705.jpg
  02. React/이승현/image/Pasted image 20240527200329.png
  02. React/이승현/image/Pasted image 20240528070630.png
Labels: 🐘이승현
