Repository FE-tech-talk/TechTalk-React, pull requests merged in 2024-06, with the labels that each got.

#20 docs: chapter 3 이승현
  03. React Hook/이승현/1.md
  03. React Hook/이승현/2.md
Labels: 🐘이승현

#16 📚 Docs: 챕터3 내용 정리
  03. React Hook/이지현/1. 리액트의 모든 훅 파헤치기.md
  03. React Hook/이지현/2. 사용자 정의 훅과 고차 컴포넌트 중 무엇을 써야 할까.md
Labels: 🥹 이지현 🥹

#17 📚 Docs: chapter 3 요약
  03. React Hook/장준혁/01. 리액트의 모든 훅 파헤치기.md
  03. React Hook/장준혁/02. 사용자 정의 훅과 고차 컴포넌트.md
Labels: 🎹 장준혁

#24 📚 Docs: chapter 4 요약
  04. Server-Side Rendering/장준혁/01. 서버 사이드 렌더링.md
  04. Server-Side Rendering/장준혁/02. 서버 사이드 렌더링을 위한 리액트 API.md
  04. Server-Side Rendering/장준혁/03. NextJs 톺아보기.md
Labels: 🎹 장준혁

#26 📚 Docs: 챕터4 내용 정리
  04. Server-Side Rendering/이지현/1. 서버 사이드 렌더링이란.md
  04. Server-Side Rendering/이지현/2. 서버 사이드 렌더링을 위한 리액트 API 살펴보기.md
  04. Server-Side Rendering/이지현/3. Next.js 톺아보기.md
Labels: 🥹 이지현 🥹

#29 docs: chapter 4 이승현
  04. Server-Side Rendering/이승현/1.md
  04. Server-Side Rendering/이승현/2.md
  04. Server-Side Rendering/이승현/20240603_134116.jpg
  04. Server-Side Rendering/이승현/20240603_145431.jpg
  04. Server-Side Rendering/이승현/20240604_121319.jpg
  04. Server-Side Rendering/이승현/20240604_121323.jpg
  04. Server-Side Rendering/이승현/3.md
Labels: 🐘이승현

#32 📚 Docs: chapter 5 요약
  05. State management/장준혁/01. 상태 관리는 왜 필요한가.md
  05. State management/장준혁/02. 리액트 훅으로 시작하는 상태 관리.md
Labels: 🎹 장준혁

#33 📚 Docs: 챕터5 내용정리
  05. State management/이지현/1. 상태 관리는 왜 필요한가.md
  05. State management/이지현/2. 리액트 훅으로 시작하는 상태 관리.md
Labels: 🥹 이지현 🥹

#38 📚 Docs: chapter 6 요약
  06. Debug/장준혁/리액트 개발 도구로 디버깅하기.md
Labels: 🎹 장준혁

#40 📚 Docs: 챕터6 내용정리
  06. Debug/이지현/1. 리액트 개발 도구로 디버깅하기.md
Labels: 🥹 이지현 🥹

#45 📚 Docs: 챕터7 내용정리
  07. Chrome dev tool/이지현/1. 개발자 도구로 React 애플리케이션 분석.md
Labels: 🥹 이지현 🥹

#44 📚 Docs: chapter 7 요약
  07. Chrome dev tool/장준혁/크롬 개발자 도구를 활용한 애플리케이션 분석.md
Labels: 🎹 장준혁

#51 📚 Docs: 챕터8 내용정리
  08. Dev Env for React/이지현/좋은 리액트 코드 작성을 위한 환경 구축하기.md
Labels: 🥹 이지현 🥹

#50 📚 Docs: chapter 8 요약
  08. Dev Env for React/장준혁/01. 좋은 리액트 코드 작성을 위한 환경 구축하기.md
  08. Dev Env for React/장준혁/02. 리액트 팀이 권장하는 테스트 라이브러리.md
Labels: 🎹 장준혁

#55 📚 Docs: 챕터 9-1, 9-2 내용정리
  09. Deploy/이지현/1. Next.js로 리액트 개발 환경 구축하기.md
  09. Deploy/이지현/2. 깃허브 100% 활용하기.md
Labels: 🥹 이지현 🥹

#56 📚 Docs: chapter 9-1, 9-2 요약
  09. Deploy/장준혁/01. NextJs로 리액트 개발 환경 구축하기.md
  09. Deploy/장준혁/02. 깃허브 활용하기.md
Labels: 🎹 장준혁

#62 📚 Docs: 챕터 9-3, 9-4 정리
  09. Deploy/이지현/3. 리액트 애플리케이션 배포하기.md
  09. Deploy/이지현/4. 리액트 애플리케이션 도커라이즈하기.md
Labels: 🥹 이지현 🥹

#61 📚 Docs: chapter 9-3, 9-4 요약
  09. Deploy/장준혁/03. 리액트 애플리케이션 배포하기.md
  09. Deploy/장준혁/04. 리액트 애플리케이션 도커라이즈하기.md
Labels: 🎹 장준혁

#64 📚 Docs: 챕터 9-3, 9-4
  09. Deploy/이승현/Deploy-2.md
Labels: 🐘이승현

#67 📚 Docs: chapter 10 요약
  10. React 17 18/장준혁/01. 리액트 17버전 살펴보기.md
  10. React 17 18/장준혁/02. 리액트 18버전 살펴보기.md
Labels: 🎹 장준혁
