Repository FE-tech-talk/TechTalk-React, pull requests merged in 2024-07, with the labels that each got.

#69 📚 Docs: 챕터10 내용정리
  10. React 17 18/이지현/1. 리액트 17 버전 살펴보기.md
  10. React 17 18/이지현/2. 리액트 18 버전 살펴보기.md
Labels: 🥹 이지현 🥹

#76 📚 Docs: 챕터11 내용정리
  11. Next.js/이지현/1. app 디렉터리의 등장.md
  11. Next.js/이지현/2. 리액트 서버 컴포넌트.md
  11. Next.js/이지현/3. Next.js에서의 리액트 서버 컴포넌트.md
  11. Next.js/이지현/4. 웹팩의 대항마, 터보팩의 등장(beta).md
  11. Next.js/이지현/5. 서버 액션(alpha).md
  11. Next.js/이지현/6. 그 밖의 변화.md
  11. Next.js/이지현/7. Next.js 13 코드 맛보기.md
Labels: 🥹 이지현 🥹

#72 📚 Docs: chapter 11 요약
  11. Next.js/장준혁/11. NextJs13과 리액트18.md
Labels: 🎹 장준혁

#77 📚 Docs: chapter 12 요약
  12. Web/장준혁/12. 웹 개발자가 관심을 가져야 할 핵심 웹 지표.md
Labels: 🎹 장준혁

#78 📚 Docs: chapter 12 정리
  12. Web/이지현/1. 웹사이트와 성능.md
  12. Web/이지현/2. 핵심 웹 지표란.md
  12. Web/이지현/3. 최대 콘텐츠풀 페인트.md
  12. Web/이지현/4. 최초 입력 지연.md
  12. Web/이지현/5. 누적 레이아웃 이동.md
Labels: 🥹 이지현 🥹

#82 📚 Docs: chapter 13 요약
  13. Web performance/장준혁/01.애플리케이션에서 확인하기.md
  13. Web performance/장준혁/02. 구글 라이트하우스.md
  13. Web performance/장준혁/03. WebPageTest.md
  13. Web performance/장준혁/04. 크롬 개발자 도구.md
Labels: 🎹 장준혁

#84 📝 Docs: 챕터 13 정리
  13. Web performance/이지현/1. 애플리케이션에서 확인하기.md
  13. Web performance/이지현/2. 구글 라이트하우스.md
  13. Web performance/이지현/3. WebPageTest.md
  13. Web performance/이지현/4. 크롬 개발자 도구.md
Labels: 🥹 이지현 🥹

#87 📚 Docs: chapter 14, 15 요약
  14. Security/장준혁/01. 리액트에서 발생하는 크로스 사이트 스크립팅.md
  14. Security/장준혁/02. getServerSideProps와 서버 컴포넌트를 주의하자.md
  14. Security/장준혁/03. a 태그의 값에 적절한 제한을 둬야한다.md
  14. Security/장준혁/04. HTTP 보안 헤더 설정하기.md
  14. Security/장준혁/05. 취약점이 있는 패키지의 사용을 피하자.md
  14. Security/장준혁/06. OWASP Top 10.md
  15. End (Future React)/장준혁/마치며.md
Labels: 🎹 장준혁

#96 📝 Docs: 14,15 정리
  14. Security/이지현/1. 리액트에서 발생하는 크로스 사이트 스크립팅(XSS).md
  14. Security/이지현/2. getServerSideProps와 서버 컴포넌트를 주의하자.md
  14. Security/이지현/3. <a>태그의 값에 적절한 제한을 둬야 한다.md
  14. Security/이지현/4. HTTP 보안 헤더 설정하기.md
  14. Security/이지현/5. 취약점이 있는 패키지의 사용을 피하자.md
  14. Security/이지현/6. OWASP Top 10.md
  15. End (Future React)/이지현/1. 리액트 프로젝트를 시작할 때 고려해야 할 사항.md
  15. End (Future React)/이지현/2. 언젠가 사라질 수도 있는 리액트.md
Labels: 🥹 이지현 🥹

#95 📚 Docs: chapter 14
  14. Security/이승현/security.md
Labels: 🐘이승현
